import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Provider from '@/app/(app)/provider';
import '@/app/globals.css';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased `}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
